<h1><?= $this->translate('A 404 error occurred') ?></h1>
<h2><?= $this->message ?></h2>

<?php if (ini_get('display_errors')) : ?>
    <?php if (isset($this->reason) && $this->reason): ?>
        <p><?= $this->translate($this->reason); ?></p>
    <?php endif ?>

    <?php if (isset($this->controller) && $this->controller): ?>

        <dl>
            <dt><?= $this->translate('Controller') ?>:</dt>
            <dd><?= $this->escapeHtml($this->controller) ?>
                <?php
                if (isset($this->controller_class)
                    && $this->controller_class
                    && $this->controller_class != $this->controller
                ) {
                    echo '(' . sprintf(
                            $this->translate('resolves to %s'),
                            $this->escapeHtml($this->controller_class)
                        ) . ')';
                }
                ?>
            </dd>
        </dl>

    <?php endif ?>

    <?php if (isset($this->exception) && $this->exception): ?>

        <h2><?= $this->translate('Exception') ?>:</h2>

        <p><b><?= $this->escapeHtml($this->exception->getMessage()) ?></b></p>

        <h3><?= $this->translate('Stack trace') ?>:</h3>

        <pre>
    <?= $this->exception->getTraceAsString() ?>
    </pre>

    <?php endif ?>
<?php endif ?>