<?php
$topNav = $this->rcmContainer()->renderContainer('topNavigation');
$mainNavigation = $this->rcmContainer()->renderContainer('mainNavigation');
$search = $this->rcmContainer()->renderContainer('search');
$rightColumn = $this->rcmContainer()->renderContainer('rightColumn');
$footer = $this->rcmContainer()->renderContainer('footer');

$this->rcmJsLibIncludeCoreJs();
$this->rcmIncludeJqueryUi();

$this->headLink()->appendStylesheet(
    $this->basePath() . '/modules/rcm-default-theme/css/theme.css',
    'screen,print'
);

echo $this->doctype();
?>
<html>
<head>
    <meta charset="utf-8">
    <?= $this->headTitle($this->metaTitle) ?>
    <?= $this->headMeta() ?>
    <?= $this->headLink() ?>
    <?= $this->headScript() ?>
</head>
