<?php

include __DIR__ . '/header.phtml';

?>

<body>
<?= $this->rcmAdminPanel; ?>
<?= $this->pwsPickThemeBar; ?>
    <!--Main Theme Body-->
    <div id="sitewrapper">
        <a href="/">
            <div id="relivlogo"></div>
        </a>


        <div id="relivTopNavigation">
            <?= $guestTopNav; ?>
        </div>


        <div id="relivNavStretchedBar">
            <div id="relivNavBar">
                <?= $guestMainNavigation ?>
            </div>
            <div id="relivSearch">
                <?= $guestSearch ?>
            </div>
        </div>

        <div style="clear: both;"></div>

        <div id="relivMainBody">
            <div id="relivHomePageContentHeader">
                <?= $this->rcmContainer()->renderPageContainer('relivHomePageContentHeader'); ?>
            </div>
            <div style="clear: both;"></div>
            <div id="relivHomeCenter">
                <?= $this->content; ?>
            </div>
            <div style="clear: both;"></div>
        </div>

        <div id="footerpush"></div>
    </div>
    <div id="relivGuestFooterContainer">
        <div id="relivGuestFooter">
            <?= $guestFooter ?>
        </div>
    </div>

    <!--Required CMS Body Bottom-->
    <?= $this->rcmBottom; ?>

    <?php if (
        !empty($_SERVER['HTTP_HOST'])
        && stripos(
            $_SERVER['HTTP_HOST'],
            'staging'
        ) === false
        && stripos(
            $_SERVER['HTTP_HOST'],
            'test'
        ) === false
        && stripos(
            $_SERVER['HTTP_HOST'],
            'dev'
        ) === false
        && stripos(
            $_SERVER['HTTP_HOST'],
            'local'
        ) === false
    ) {
        ?>

        <script type="text/javascript">

            var _gaq = _gaq || [];
            _gaq.push(['_setAccount', 'UA-12357964-1']);
            _gaq.push(['_setDomainName', '<?=  $_SERVER['HTTP_HOST'] ?>']);
            _gaq.push(['_setAllowLinker', true]);
            _gaq.push(['_trackPageview']);

            (function () {
                var ga = document.createElement('script');
                ga.type = 'text/javascript';
                ga.async = true;
                ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
                var s = document.getElementsByTagName('script')[0];
                s.parentNode.insertBefore(ga, s);
            })();

        </script>

    <?php } ?>
</body>
</html>
