<?php require __DIR__ . '/header.phtml' ?>

<body>
<?= $this->rcmAdminPanel; ?>
    <!--Main Theme Body-->
    <div id="sitewrapper">

        <div id="header">
            <?= $header ?>
        </div>

        <div id="navigation">
            <?= $navigation ?>
        </div>

        <div id="mainBody">
            <div id="leftColumn">
                <?= $leftColumn ?>
            </div>

            <div id="centerColumn">
                <?= $this->content; ?>
            </div>

            <div id="rightColumn">
                <?= $rightColumn ?>
            </div>
        </div>

        <div id="footer">
            <div id="mainFooter">
                <?= $footer ?>
            </div>
        </div>
    </div>

    <!--Required CMS Body Bottom-->
    <?= $this->rcmBottom; ?>

<!--[if lt IE 9]><script type="text/javascript" src="/modules/rcm-twitter-bootstrap/html5shiv/html5shiv.js"></script><![endif]-->
<!--[if lt IE 9]><script type="text/javascript" src="/modules/rcm-twitter-bootstrap/bootstrap/js/respond/respond.min.js"></script><![endif]-->
</body>
</html>
